import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from 'three';
import {makePrimitive,makeCube,primitiveDensity} from '../src/primitive-factory.js';
import {makeTextObject} from '../src/text-object-core.js';
const font=JSON.parse(fs.readFileSync(new URL('../src/fonts/helvetiker_regular.typeface.json',import.meta.url)));
function closed(mesh){for(const edge of mesh.edges()){assert.equal(edge.faces.length,2);const directions=edge.faces.map(fi=>{const f=mesh.faces[fi];return f.some((a,i)=>a===edge.a&&f[(i+1)%f.length]===edge.b)?1:-1;});assert.equal(directions[0]+directions[1],0);}for(let i=0;i<mesh.faces.length;i++)assert.ok(mesh.faceNormal(i).length()>.99);assert.ok(mesh.vertices.every(v=>v.toArray().every(Number.isFinite)));}
function volume(mesh){let sum=0;for(const f of mesh.faces)for(let i=1;i<f.length-1;i++)sum+=mesh.vertices[f[0]].dot(mesh.vertices[f[i]].clone().cross(mesh.vertices[f[i+1]]))/6;return sum;}
for(const type of Object.keys(primitiveDensity))test(`Add ${type}: each density axis changes actual face count with valid topology`,()=>{const a=makePrimitive(type,{x:8,y:4}),b=makePrimitive(type,{x:9,y:4}),c=makePrimitive(type,{x:8,y:5});assert.ok(b.faces.length>a.faces.length);assert.ok(c.faces.length>a.faces.length);if(type==='plane'){assert.equal(a.faces.length,32);assert.ok(a.faces.every((_,i)=>a.faceNormal(i).y>.99));}else{closed(a);closed(b);closed(c);assert.ok(volume(a)>0);}if(type==='cube')assert.ok(Math.abs(volume(a)-8)<1e-9);});
test('legacy default and Low/Medium/High primitive APIs keep original counts',()=>{assert.equal(makePrimitive('cube').faces.length,6);assert.equal(makePrimitive('plane').faces.length,1);for(const [detail,x,y] of [['low',8,4],['medium',12,6],['high',16,8]]){assert.equal(makePrimitive('cylinder',detail).faces.length,x+2);assert.equal(makePrimitive('cone',detail).faces.length,x+1);assert.equal(makePrimitive('sphere',detail).faces.length,x*y);assert.equal(makePrimitive('torus',detail).faces.length,x*y);}});
test('asymmetric cube grid welds every face boundary and preserves exact box',()=>{const m=makeCube(2,7,3);closed(m);assert.equal(m.faces.length,102);assert.equal(new Set(m.vertices.map(v=>v.toArray().join(','))).size,m.vertices.length);assert.ok(Math.abs(volume(m)-8)<1e-9);});
for(const word of ['BOX','B8O','Hello','i j','Architecture','0123456789'])test(`Text ${word} is one editable closed mesh with outward winding`,()=>{const m=makeTextObject(font,word,{thickness:.4,x:4,y:3});closed(m);assert.ok(volume(m)>0);assert.equal(m.faceGroups.length,m.faces.length);const box=new THREE.Box3().setFromPoints(m.vertices);assert.ok(Math.abs(box.max.z-box.min.z-.4)<1e-9);assert.ok(box.getCenter(new THREE.Vector3()).length()<1e-9);});
test('Text depth scales exact solid volume and depth bands preserve it',()=>{const a=makeTextObject(font,'BOX',{thickness:.2}),b=makeTextObject(font,'BOX',{thickness:.6,y:4});assert.ok(Math.abs(volume(b)/volume(a)-3)<1e-8);assert.ok(b.faces.length>a.faces.length);closed(b);});
test('Text holes remain empty through the thickness',()=>{const m=makeTextObject(font,'O'),geometry=m.triangulatedGeometry(),object=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));object.updateMatrixWorld();const ray=new THREE.Raycaster(new THREE.Vector3(0,0,2),new THREE.Vector3(0,0,-1));assert.equal(ray.intersectObject(object).length,0);ray.ray.origin.x=.42;assert.ok(ray.intersectObject(object).length>0);geometry.dispose();object.material.dispose();});
test('Text refuses blank/unsupported/oversized words and invalid thickness',()=>{for(const word of ['', '   ','😀','a'.repeat(65)])assert.throws(()=>makeTextObject(font,word));for(const thickness of [0,-1,NaN,Infinity,101])assert.throws(()=>makeTextObject(font,'Box',{thickness}));});
