import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {EditableMesh,knife} from './helpers/modelling-combinations-runtime.mjs';
import {parseEditableOBJ} from '../src/obj-facegroups-core.js';import {History} from '../src/history.js';
import {fixture as controller} from './helpers/face-bevel-geometry-runtime.mjs';
const parsed=parseEditableOBJ(fs.readFileSync(new URL('./fixtures/loop-cut-746.obj',import.meta.url),'utf8'))[0].mesh;
const cage=()=>new EditableMesh(parsed.vertices,parsed.faces,parsed.creases,parsed.faceGroups);
const snap=m=>({v:m.vertices.map(v=>v.toArray()),f:Array.from(m.faces,f=>Array.from(f)),g:Array.from(m.faceGroups),c:Array.from(m.creases),le:Array.from(m.looseEdges||[]),lv:Array.from(m.looseVertices||[])});
function closed(m){assert.equal(m.faceGroups.length,m.faces.length);assert.ok(m.vertices.every(v=>Number.isFinite(v.x+v.y+v.z)));for(const f of m.faces){assert.ok(f.length>=3);assert.equal(new Set(f).size,f.length);}for(const e of m.edges()){if(e.loose)continue;assert.equal(e.faces.length,2,`boundary ${e.a}:${e.b}`);const dirs=e.faces.map(fi=>m.faces[fi].some((v,k)=>v===e.a&&m.faces[fi][(k+1)%m.faces[fi].length]===e.b));assert.notEqual(dirs[0],dirs[1]);}}
function loop(m){const cut=m.loopCut(0,.5),v=new Set(cut.slideData.map(x=>x.vertex)),ids=m.edges().flatMap((e,i)=>v.has(e.a)&&v.has(e.b)?[i]:[]);return m.bevelEdgeLoopInfo(ids).edgesInOrder.map(e=>e.edgeIndex);}
for(const segments of [1,2,3,4])test(`all 35 partial supplied-cage loops execute Bevel ${segments} with closed directed end caps`,()=>{const m=cage(),order=loop(m);assert.equal(order.length,7);for(let start=0;start<7;start++)for(let count=2;count<7;count++){const ids=Array.from({length:count},(_,i)=>order[(start+i)%7]),trial=m.clone();assert.equal(trial.generalBevelSelectionInfo(ids)?.mode,'connected');assert.ok(trial.generalBevelSelection(ids,.2,segments));closed(trial);assert.equal(trial.faces.filter(f=>f.length===3).length,segments===1?2:0);}});
test('partial-chain routing and geometry are independent of edge order and duplicate selection IDs',()=>{const m=cage(),order=loop(m),ids=order.slice(0,3),a=m.clone(),b=m.clone();assert.ok(a.generalBevelSelection(ids,.2,3));assert.ok(b.generalBevelSelection([...ids].reverse().concat(ids[0]),.2,3));closed(a);closed(b);const geometry=t=>t.faces.map(f=>f.map(i=>t.vertices[i].toArray().map(x=>x.toFixed(7)).join(',')).sort().join('|')).sort();assert.deepEqual(geometry(a),geometry(b));});
test('partial-chain cap inherits unanimous groups, retains loose data and valid split creases',()=>{const m=cage();m.faceGroups.fill('Body');const ids=loop(m),edges=m.edges();const selectedVertices=new Set(ids.slice(0,3).flatMap(i=>[edges[i].a,edges[i].b]));const rail=edges.find(e=>selectedVertices.has(e.a)!==selectedVertices.has(e.b));m.creases.set(m.edgeKey(rail.a,rail.b),.7);m.vertices.push(m.vertices[0].clone().addScalar(100));const loose=m.vertices.length-1;m.looseVertices=new Set([loose]);assert.ok(m.generalBevelSelection(ids.slice(0,3),.2,3));closed(m);assert.ok(m.faceGroups.every(g=>g==='Body'));assert.equal(m.looseVertices.size,1);assert.ok([...m.creases.values()].includes(.7));for(const key of m.creases.keys())assert.ok(m.edges().some(e=>m.edgeKey(e.a,e.b)===key));});
test('actual Edge preview Apply/Cancel retains partial-chain selection and one-step history',()=>{for(const action of ['apply','cancel']){const m=cage(),ids=loop(m).slice(0,3),f=controller(m),before=snap(m);f.setMode('edge');f.setIds(ids);f.node('#bevelBtn').listeners.get('click')({preventDefault(){},stopImmediatePropagation(){}});f.launch();f.node('#bevelSegments').value='3';f.node('#bevelSegments').listeners.get('input')();f.action(action);if(action==='cancel'){assert.deepEqual(snap(m),before);assert.deepEqual(Array.from(f.ids()),ids);assert.equal(f.context.__boxlabHistory.undoStack.length,0);}else{closed(m);assert.equal(f.context.__boxlabHistory.undoStack.length,1);const after=snap(m),undo=f.context.__boxlabHistory.undo(m);assert.deepEqual(snap(undo),before);assert.deepEqual(snap(f.context.__boxlabHistory.redo(undo)),after);}}});
test('rotated translated and scaled supplied cage retains directed chain caps',()=>{const m=cage(),ids=loop(m).slice(0,4),axis=m.vertices[0].clone().set(1,3,2).normalize();m.vertices.forEach(v=>v.applyAxisAngle(axis,.7).multiplyScalar(4).addScalar(10000));assert.ok(m.generalBevelSelection(ids,.4,4));closed(m);});
test('four-way turns and branching junctions refuse without changing the mesh',()=>{const m=cage(),order=loop(m),edges=m.edges(),first=edges[order[0]],rail=edges.findIndex(e=>e.faces.some(fi=>first.faces.includes(fi))&&(e.a===first.a||e.b===first.a)&&m.edgeKey(e.a,e.b)!==m.edgeKey(first.a,first.b));const ids=[order[0],rail],before=snap(m);assert.equal(m.generalBevelSelectionInfo(ids),null);assert.equal(m.generalBevelSelection(ids,.2,3),null);assert.deepEqual(snap(m),before);const star=edges.flatMap((e,i)=>e.a===first.a||e.b===first.a?[i]:[]);assert.equal(m.generalBevelSelection(star,.2,3),null);assert.deepEqual(snap(m),before);});
test('Knife after a partial rounded chain, then another Loop, has exact Undo/Redo',()=>{let m=cage();const ids=loop(m).slice(0,3),h=new History(),states=[snap(m)];const before=m.clone();assert.ok(m.generalBevelSelection(ids,.2,3));h.push(before);closed(m);states.push(snap(m));knife(m,h,m.faces.findIndex(f=>f.length===4));closed(m);states.push(snap(m));const seed=m.edges().findIndex((_,i)=>m.clone().loopCut(i,.6));assert.ok(seed>=0);const pre=m.clone();assert.ok(m.loopCut(seed,.6));h.push(pre);closed(m);states.push(snap(m));for(let i=states.length-2;i>=0;i--){m=h.undo(m);assert.deepEqual(snap(m),states[i]);}for(let i=1;i<states.length;i++){m=h.redo(m);assert.deepEqual(snap(m),states[i]);}});
