import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import * as THREE from 'three';
import {EditableMesh} from './helpers/modelling-combinations-runtime.mjs';import {History} from '../src/history.js';
const source=fs.readFileSync(new URL('../src/knife-tool.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
function owner(mesh){const listeners=new Map(),status={},node={classList:{add(){},remove(){}},dispatchEvent(){},releasePointerCapture(){},addEventListener:(t,f)=>listeners.set(t,f)};const h=new History();const ctx={THREE,Map,Set,document:{querySelector:s=>s==='#selectionStatus'?status:node,addEventListener(){}},window:{addEventListener(){},dispatchEvent(){}},Event:class{},CustomEvent:class{},__boxlabBridgeState:{mesh},__boxlabHistory:h,__boxlabSelectionBridge:{mode:()=> 'face'}};vm.createContext(ctx);vm.runInContext(source+'\nglobalThis.startCut=(start,end)=>{drag={mesh:globalThis.__boxlabBridgeState.mesh,object:globalThis.__boxlabObjectManager?.activeId,id:1,x:0,y:0,start};endpointWithHysteresis=()=>end;};',ctx);return{h,status,cut:(start,end)=>{ctx.startCut(start,end);listeners.get('pointerup')({pointerId:1,clientX:100,clientY:0,preventDefault(){},stopImmediatePropagation(){}});}};}
const shape=(points,face=points.map((_,i)=>i))=>new EditableMesh(points.map(([x,y])=>new THREE.Vector3(x,y,0)),[face],null,['Body']);
const snap=m=>({v:m.vertices.map(v=>v.toArray()),f:Array.from(m.faces,f=>Array.from(f)),g:Array.from(m.faceGroups),c:[...m.creases],le:[...(m.looseEdges||[])],lv:[...(m.looseVertices||[])]});
const vertex=vertex=>({kind:'vertex',snapType:'END',vertex});
const edge=(m,a,b,t=.5)=>({kind:'edge',snapType:'MID',key:m.edgeKey(a,b),faceA:a,faceB:b,t});
const notch=()=>shape([[0,0],[3,0],[3,3],[2,3],[2,1],[1,1],[1,3],[0,3]]);
test('actual Knife rejects a diagonal across the exterior notch, despite a shared source face',()=>{const m=notch(),f=owner(m),before=snap(m);assert.equal(m.clone().connectVertices(3,6).ok,true);f.cut(vertex(3),vertex(6));assert.deepEqual(snap(m),before);assert.equal(f.h.undoStack.length,0);assert.match(f.status.textContent,/could not make a clean cut/);});
test('actual Knife rejects crossing notch with split edge endpoints and restores source/creases/redo',()=>{const m=notch(),f=owner(m);m.creases.set(m.edgeKey(2,3),.7);f.h.push(m);const undone=f.h.undo(m);Object.assign(m,undone);const before=snap(m),redo=f.h.redoStack.length;f.cut(edge(m,2,3),edge(m,6,7));assert.deepEqual(snap(m),before);assert.equal(f.h.redoStack.length,redo);assert.equal(f.h.undoStack.length,0);});
for(const reverse of [false,true])test(`valid diagonal stays inside concave face; reverse winding ${reverse}, groups/history preserved`,()=>{const m=notch();if(reverse)m.faces[0].reverse();const f=owner(m),before=snap(m);f.cut(vertex(0),vertex(4));assert.equal(m.faces.length,2);assert.deepEqual(m.faceGroups,['Body','Body']);assert.equal(f.h.undoStack.length,1);const after=snap(m),undo=f.h.undo(m);assert.deepEqual(snap(undo),before);assert.deepEqual(snap(f.h.redo(undo)),after);});
test('Knife rejects a collinear subdivided boundary instead of creating a zero-area face',()=>{const m=shape([[0,0],[1,0],[2,0],[2,2],[0,2]]),f=owner(m),before=snap(m);assert.equal(m.clone().connectVertices(0,2).ok,true);f.cut(vertex(0),vertex(2));assert.deepEqual(snap(m),before);assert.equal(f.h.undoStack.length,0);});
test('Knife refuses diagonal through a third existing boundary vertex',()=>{const m=notch(),f=owner(m),before=snap(m);f.cut(vertex(0),vertex(2));assert.deepEqual(snap(m),before);assert.equal(f.h.undoStack.length,0);});
for(const scale of [.001,1000])test(`rotated/translated concave polygon at scale ${scale} retains valid cuts and refuses exterior chord`,()=>{const axis=new THREE.Vector3(1,2,3).normalize(),m=notch();m.vertices.forEach(v=>v.applyAxisAngle(axis,.8).multiplyScalar(scale).addScalar(10000));const f=owner(m),before=snap(m);f.cut(vertex(3),vertex(6));assert.deepEqual(snap(m),before);f.cut(vertex(0),vertex(4));assert.equal(m.faces.length,2);assert.equal(f.h.undoStack.length,1);});
test('nonplanar source face refuses unchanged',()=>{const m=notch();m.vertices[4].z=.2;const f=owner(m),before=snap(m);f.cut(vertex(0),vertex(4));assert.deepEqual(snap(m),before);assert.equal(f.h.undoStack.length,0);});
test('splitter exception restores groups, topology and loose metadata without clearing redo',()=>{const m=EditableMesh.cube();m.faceGroups.fill('Body');m.looseEdges=new Set();m.looseVertices=new Set();const f=owner(m),before=snap(m);f.h.push(m);Object.assign(m,f.h.undo(m));const redo=f.h.redoStack.length;let calls=0;m.connectVertices=function(){calls++;this.faces[0].reverse();this.faceGroups[0]='broken';this.looseVertices.add(0);throw Error('failure');};f.cut(edge(m,0,1),edge(m,2,3));assert.equal(calls,1);assert.deepEqual(snap(m),before);assert.equal(f.h.undoStack.length,0);assert.equal(f.h.redoStack.length,redo);});
