import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {EditableMesh} from './helpers/modelling-combinations-runtime.mjs';
import {knifeScreenRuntime} from './helpers/knife-screen-runtime.mjs';
const snapshot=m=>({v:m.vertices.map(v=>v.toArray()),f:Array.from(m.faces,f=>Array.from(f)),g:Array.from(m.faceGroups),c:[...m.creases],le:[...m.looseEdges||[]],lv:[...m.looseVertices||[]]});
function fixture(){const m=EditableMesh.cube();m.faceGroups.fill('Shell');const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,0,8);camera.updateMatrixWorld();const f=knifeScreenRuntime(m,camera),a=f.point(4,5,.3),b=f.point(6,7,.6);a.y-=2;b.y+=2;f.ctx.__boxlabHistory.redoStack.push(m.clone());f.arm();f.pointer('pointerdown',a);f.pointer('pointermove',b);return {m,f,b};}
for(const phase of ['pointermove','pointerup','bridge'])for(const change of ['coordinate','vertex-count','face-order','face-count'])test(`Knife ${phase} refuses stale same-object ${change} and preserves newer edit/history`,()=>{const {m,f,b}=fixture();if(change==='coordinate')m.vertices[0].x+=.1;else if(change==='vertex-count')m.vertices.push(new THREE.Vector3(3,4,5));else if(change==='face-order')m.faces[0].reverse();else m.faces.push([0,1,2]);const current=snapshot(m);if(phase==='bridge')f.emitWindow('boxlab-bridge-state');else f.pointer(phase,b);f.pointer('pointerup',b);assert.deepEqual(snapshot(m),current);assert.equal(f.ctx.__boxlabKnifeTool.armed(),false);assert.equal(f.ctx.__boxlabHistory.undoStack.length,0);assert.equal(f.ctx.__boxlabHistory.redoStack.length,1);assert.equal(f.captures.size,0);assert.equal(f.markers.size,0);});
test('Knife unchanged-value geometry arrays and latest labels/creases remain valid on release',()=>{const {m,f,b}=fixture();m.vertices=m.vertices.map(v=>v.clone());m.faces=m.faces.map(face=>[...face]);m.faceGroups.fill('Latest');m.creases.set('4:5',.8);f.emitWindow('boxlab-bridge-state');assert.equal(f.ctx.__boxlabKnifeTool.armed(),true);f.pointer('pointerup',b);assert.equal(f.ctx.__boxlabHistory.undoStack.length,1);assert.equal(f.ctx.__boxlabKnifeTool.armed(),true);assert.ok(m.faceGroups.every(g=>g==='Latest'));assert.equal(f.ctx.__boxlabHistory.undoStack[0].creases.get('4:5'),.8);assert.equal(f.captures.size,0);});
