import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {EditableMesh} from './helpers/modelling-combinations-runtime.mjs';import {parseEditableOBJ} from '../src/obj-facegroups-core.js';import {History} from '../src/history.js';
const parsed=parseEditableOBJ(fs.readFileSync(new URL('./fixtures/loop-cut-746.obj',import.meta.url),'utf8'))[0].mesh;
const fixture=()=>new EditableMesh(parsed.vertices,parsed.faces,parsed.creases,parsed.faceGroups);
const snap=m=>({v:m.vertices.map(v=>v.toArray()),f:Array.from(m.faces,f=>Array.from(f)),g:Array.from(m.faceGroups),c:Array.from(m.creases)});
const volume=m=>m.faces.reduce((sum,f)=>{const a=m.vertices[f[0]];for(let i=1;i<f.length-1;i++)sum+=a.dot(m.vertices[f[i]].clone().cross(m.vertices[f[i+1]]))/6;return sum},0);
function closed(m){for(const e of m.edges()){assert.equal(e.faces.length,2);const dirs=e.faces.map(fi=>m.faces[fi].some((v,i)=>v===e.a&&m.faces[fi][(i+1)%m.faces[fi].length]===e.b)?1:-1);assert.notEqual(dirs[0],dirs[1]);}assert.equal(m.faceGroups.length,m.faces.length);assert.ok(m.faces.every(f=>f.length>=4&&new Set(f).size===f.length));}
test('uploaded31vertex24face cage: rejected seed has no native quad path',()=>{const m=fixture();assert.equal(m.vertices.length,31);assert.equal(m.faces.length,24);assert.equal(m.loopRing(0),null);});
for(const t of [.15,.5,.75])test(`red-line seed single cut at ${t} traverses all seven polygons, retains volume`,()=>{const m=fixture(),v=volume(m),r=m.loopCut(0,t);assert.equal(r.parallelPolygonStrip,true);assert.equal(r.splitFaces,7);assert.equal(r.slideData.length,7);closed(m);assert.ok(Math.abs(volume(m)-v)<1e-7);const points=r.slideData.map(item=>m.vertices[item.vertex].y);assert.ok(points.every(y=>Math.abs(y-points[0])<1e-9));});
for(const count of [2,3,8])test(`red-line ${count} cuts share polygon boundaries and preserve volume`,()=>{const m=fixture(),v=volume(m),r=m.loopCuts(0,count);assert.equal(r.parallelPolygonStrip,true);assert.equal(r.slideGroups.length,count);closed(m);assert.ok(Math.abs(volume(m)-v)<1e-7);assert.equal(m.faces.length,24+7*count);});
test('plane-preserving Slide and exact Undo/Redo; one operation snapshot',()=>{const m=fixture(),h=new History(),before=snap(m);h.push(m);const r=m.loopCut(0,.5);assert.ok(m.loopSlide(r.slideData,.8));closed(m);assert.ok(r.slideData.every(item=>Math.abs(m.vertices[item.vertex].y-m.vertices[r.slideData[0].vertex].y)<1e-9));const after=snap(m),undo=h.undo(m);assert.deepEqual(snap(undo),before);assert.deepEqual(snap(h.redo(undo)),after);});
test('new strip preserves original boundary subdivisions, facegroups and creases',()=>{const m=fixture();m.faceGroups=m.faces.map((_,i)=>`g${i}`);m.creases.set(m.edgeKey(0,2),.7);const old=m.vertices.map(v=>v.clone()),r=m.loopCut(0,.5);closed(m);old.forEach((v,i)=>assert.ok(m.vertices[i].equals(v)));assert.equal(m.faceGroups.filter(g=>g==='g0').length,2);assert.equal([...m.creases.values()].filter(v=>v===.7).length,2);assert.equal(r.slideData.length,7);});
test('rotated/translated/scaled supplied cage follows same topology',()=>{const m=fixture(),axis=m.vertices[0].clone().set(1,2,3).normalize();m.vertices.forEach(v=>v.applyAxisAngle(axis,.53).multiplyScalar(3).addScalar(200));const r=m.loopCut(0,.5);assert.equal(r.parallelPolygonStrip,true);closed(m);});
test('unsupported cut through existing vertices or an open shell refuses unchanged',()=>{for(const modify of [m=>m.faces.pop(),m=>m.vertices[2].y=3]){const m=fixture();modify(m);const before=snap(m);assert.equal(m.loopCut(0,.5),null);assert.deepEqual(snap(m),before);}});
test('ordinary cube keeps native quad placement and four-face ring',()=>{const m=EditableMesh.cube(),r=m.loopCut(0,.7);assert.equal(r.parallelPolygonStrip,undefined);assert.equal(r.position,.7);assert.equal(r.splitFaces,4);closed(m);});

const source=fs.readFileSync(new URL('../src/loop-cut-commit.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'');
test('supplied n-gon strip uses actual protected Loop commit owner with retained selection/history',()=>{
 const history=new History();let mesh=fixture(),before=mesh.clone();history.push(before);const cut=mesh.loopCut(0,.5);assert.equal(cut.parallelPolygonStrip,true);assert.ok(mesh.loopSlide(cut.slideData,.7));const placed=mesh.clone(),vertices=new Set(cut.slideData.map(i=>i.vertex));let edgeObjects=new Map(mesh.edges().map((e,i)=>[i,{material:{color:{getHex:()=>vertices.has(e.a)&&vertices.has(e.b)?0xffe14a:0}}}]));
 let release,ids=[],radial=true;const state={mesh,edgeObjects},canvas={addEventListener:(t,f)=>release=f},status={};
 const ctx={Map,Set,document:{querySelector:q=>q==='#viewport'?canvas:q==='#loopCutBtn'?{classList:{contains:()=>true}}:q==='#selectionStatus'?status:{click:()=>{mesh=q==='#undoBtn'?history.undo(mesh):history.redo(mesh);state.mesh=mesh;state.edgeObjects=new Map();}}},__boxlabBridgeState:state,__boxlabSelectionBridge:{set:(mode,next)=>{ids=next;}},__boxlabMainDirectTool:{busy:()=>false},__boxlabEdgeViewportSession:{loopActive:()=>radial},queueMicrotask:f=>f(),setTimeout:f=>f()};
 vm.runInNewContext(source,ctx);release({isPrimary:true});assert.equal(ctx.__boxlabLoopCutCommit.pending(),true);assert.equal(state.mesh,mesh);assert.equal(history.undoStack.length,1);
 assert.equal(ctx.__boxlabLoopCutCommit.commitCurrent(),true);assert.deepEqual(state.mesh.vertices,placed.vertices);assert.deepEqual(state.mesh.faces,placed.faces);assert.ok(ids.length);assert.equal(ctx.__boxlabLoopCutCommit.pending(),false);assert.equal(history.undoStack.length,1);const undone=history.undo(state.mesh);assert.deepEqual(undone,before);assert.deepEqual(history.redo(undone),placed);
});
test('all thirteen vertical seed segments complete the ring instead of stopping at n-gons',()=>{const source=fixture();let count=0;source.edges().forEach((e,i)=>{const d=source.vertices[e.b].clone().sub(source.vertices[e.a]);if(Math.abs(d.x)+Math.abs(d.z)>1e-8)return;const m=source.clone(),r=m.loopCut(i,.5);assert.equal(r.parallelPolygonStrip,true);assert.equal(r.splitFaces,7);closed(m);count++;});assert.equal(count,13);});
test('non-planar affected polygon refuses with source unchanged',()=>{const m=fixture();m.vertices[4].z+=.1;const before=snap(m);assert.equal(m.loopCut(0,.5),null);assert.deepEqual(snap(m),before);});
