import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {EditableMesh,knife} from './helpers/modelling-combinations-runtime.mjs';
import {parseEditableOBJ} from '../src/obj-facegroups-core.js';import {History} from '../src/history.js';import {installBevelWatertightGuard} from '../src/bevel-watertight-guard.js';
const p=parseEditableOBJ(fs.readFileSync(new URL('./fixtures/loop-cut-746.obj',import.meta.url),'utf8'))[0].mesh;
const cage=()=>new EditableMesh(p.vertices,p.faces,p.creases,p.faceGroups);
const snapshot=m=>JSON.stringify({v:m.vertices.map(v=>v.toArray()),f:m.faces,g:m.faceGroups,c:[...m.creases],le:[...(m.looseEdges||[])],lv:[...(m.looseVertices||[])]});
function closed(m){assert.equal(m.faceGroups.length,m.faces.length);for(const f of m.faces)assert.equal(new Set(f).size,f.length);for(const e of m.edges()){if(e.loose)continue;assert.equal(e.faces.length,2);const dirs=e.faces.map(fi=>m.faces[fi].some((v,k)=>v===e.a&&m.faces[fi][(k+1)%m.faces[fi].length]===e.b));assert.notEqual(dirs[0],dirs[1]);}}
for(const segments of [1,3])test(`supplied cage after polygon Loop: all 67 eligible edges Bevel ${segments} remain closed and oriented`,()=>{const m=cage();assert.ok(m.loopCut(0,.5));let n=0;for(let i=0;i<m.edges().length;i++){const trial=m.clone();if(!trial.generalBevelSelectionInfo([i]))continue;assert.ok(trial.generalBevelSelection([i],.04,segments),`edge ${i}`);closed(trial);n++;}assert.equal(n,67);});
test('Knife on every quad of the supplied loop cage retains shared boundaries and exact history',()=>{const m=cage();m.loopCut(0,.5);let n=0;for(let fi=0;fi<m.faces.length;fi++){if(m.faces[fi].length!==4)continue;const trial=m.clone(),h=new History(),before=snapshot(trial);knife(trial,h,fi);assert.equal(h.undoStack.length,1);closed(trial);const after=snapshot(trial),undo=h.undo(trial);assert.equal(snapshot(undo),before);assert.equal(snapshot(h.redo(undo)),after);n++;}assert.ok(n>10);});
for(const segments of [1,3])test(`supplied cage Loop → Knife → Bevel ${segments} → Loop preserves every Undo/Redo state`,()=>{let m=cage();const h=new History(),states=[snapshot(m)];const op=fn=>{const before=m.clone();assert.ok(fn());closed(m);h.push(before);states.push(snapshot(m));};op(()=>m.loopCut(0,.5));knife(m,h,m.faces.findIndex(f=>f.length===4));closed(m);states.push(snapshot(m));const edge=m.edges().findIndex((_,i)=>m.clone().generalBevelSelection([i],.04,segments));op(()=>m.generalBevelSelection([edge],.04,segments));const seed=m.edges().findIndex((_,i)=>m.clone().loopCut(i,.6));assert.ok(seed>=0);op(()=>m.loopCut(seed,.6));for(let i=states.length-2;i>=0;i--){m=h.undo(m);assert.equal(snapshot(m),states[i]);}for(let i=1;i<states.length;i++){m=h.redo(m);assert.equal(snapshot(m),states[i]);}});
test('Bevel guard rejects a reversed face despite unchanged two-owner edge counts, restores all metadata',()=>{class Broken extends EditableMesh{};Broken.prototype.__bevelWatertightGuardInstalled=false;Broken.prototype.generalBevelSelection=function(){this.faces[0].reverse();this.faceGroups[0]='broken';this.creases.set('0:1',.9);this.looseVertices.add(7);return {ok:true};};installBevelWatertightGuard(Broken);const m=new Broken(EditableMesh.cube().vertices,EditableMesh.cube().faces);m.looseVertices=new Set();const before=snapshot(m);assert.equal(m.generalBevelSelection([0],.1,1),null);assert.match(m.__lastBevelError,/reverse a shared face boundary/);assert.equal(snapshot(m),before);closed(m);});
test('Bevel guard does not impose closed winding on an existing open surface',()=>{class Open extends EditableMesh{};Open.prototype.__bevelWatertightGuardInstalled=false;Open.prototype.generalBevelSelection=function(){return {ok:true};};installBevelWatertightGuard(Open);const cube=EditableMesh.cube(),m=new Open(cube.vertices,cube.faces.slice(1));assert.deepEqual(m.generalBevelSelection([0],.1,1),{ok:true});});
