import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as THREE from 'three';
const read=n=>fs.readFileSync(new URL('../src/'+n,import.meta.url),'utf8');
const gizmo=read('total-gizmo.js');
function fn(s,name,next){return s.slice(s.indexOf(`function ${name}(`),s.indexOf(`function ${next}(`));}
// Only extract the hit function (the following canvas bindings need a DOM).
function hitFunction(){return gizmo.slice(gizmo.indexOf('function objectHitAt('),gizmo.indexOf("canvas?.addEventListener('pointerdown',event=>{",gizmo.indexOf('function objectHitAt(')));}
function context(){const mesh=x=>({vertices:[new THREE.Vector3(x,0,0),new THREE.Vector3(x+2,0,0)]});const live=mesh(10),a={id:1,visible:true,mesh:mesh(0)},b={id:2,visible:true,mesh:mesh(100)};const c={THREE,currentMode:()=> 'object',state:()=>({mesh:live}),__boxlabObjectManager:{activeId:1,objects:[a,b]},__boxlabObjectSelection:{multi:true,ids:new Set([2,1])}};vm.createContext(c);vm.runInContext(fn(gizmo,'objectSelected','componentVertexIndices')+fn(gizmo,'componentVertexIndices','selectionAvailable')+fn(gizmo,'selectionKey','setHubState')+fn(gizmo,'centerOf','screenPoint')+hitFunction(),c);return {c,live,a,b};}
test('Multi display follows insertion order, not scene order; removal and live active geometry follow owners',()=>{const {c,live,b}=context();assert.equal(c.centerOf(live).x,101);b.mesh.vertices.forEach(v=>v.x+=3);assert.equal(c.centerOf(live).x,104);c.__boxlabObjectSelection.ids.delete(2);assert.equal(c.centerOf(live).x,11);c.__boxlabObjectSelection.multi=false;assert.equal(c.centerOf(live).x,11);});
test('Actual Multi membership changes restore gizmo key; empty Multi has no selection',()=>{const {c,live}=context();const key=c.selectionKey(live);c.__boxlabObjectSelection.ids.delete(2);assert.notEqual(c.selectionKey(live),key);assert.equal(c.objectSelected(),true);c.__boxlabObjectSelection.ids.clear();assert.equal(c.objectSelected(),false);});
test('Inactive Object hits are not background; scene picker is authoritative',()=>{const {c}=context();c.__boxlabSelectionBridge={pickObject:()=>null};c.__boxlabObjectManager.pickObject=()=>({id:2});assert.equal(c.objectHitAt({}),true);c.__boxlabObjectManager.pickObject=()=>null;assert.equal(c.objectHitAt({}),false);});
test('Activation and gizmo share nearest visible scene hit, with existing tie tolerance',()=>{const s=read('multi-object.js');let active=5,inactive=3;const c={currentMode:()=> 'object',state:()=>({camera:{}}),setPointer(){},pointer:{},activeId:1,activeBody:{visible:true},inactiveBodies:[{visible:true},{visible:false}],OBJECT_HIT_EPSILON:.001,raycaster:{setFromCamera(){},intersectObject:()=>active==null?[]:[{distance:active}],intersectObjects:bodies=>{assert.equal(bodies.length,1);return inactive==null?[]:[{distance:inactive,object:{userData:{objectId:2}}}];}}};vm.createContext(c);vm.runInContext(fn(s,'pickViewportObject','handleViewportActivation'),c);assert.equal(c.pickViewportObject({}).id,2);inactive=6;assert.equal(c.pickViewportObject({}).id,1);active=null;inactive=null;assert.equal(c.pickViewportObject({}),null);});
test('Pencil semantic does not dismiss an inactive operand; original background dismissal remains',()=>{const {c}=context();let listener;Object.assign(c,{window:{addEventListener:(name,fn)=>listener=fn},hubState:'transform',objectTransformDismissed:false,root:{dataset:{},hidden:false},expanded:true,resetTransientState(){},gestureDebug(){}});const a=gizmo.indexOf("window.addEventListener('boxlab-pencil-background-tap'");const b=gizmo.indexOf('\n});',a)+4;vm.runInContext(gizmo.slice(a,b),c);c.__boxlabObjectManager.pickObject=()=>({id:2});listener({detail:{clientX:20,clientY:20}});assert.equal(c.objectTransformDismissed,false);c.__boxlabObjectManager.pickObject=()=>null;listener({detail:{clientX:20,clientY:20}});assert.equal(c.objectTransformDismissed,true);assert.equal(c.root.hidden,true);});
