import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const read=n=>fs.readFileSync(new URL('../src/'+n,import.meta.url),'utf8');
function fixture(file){
 const fields=new Map(),handlers=new Map(),jobs=[],calls=[],events=[];let mode=file.includes('face-value')?'face':'edge',ids=[1,2],locked=false;
 function el(){return{hidden:false,disabled:false,value:'20',textContent:'',style:{},listeners:new Map(),classList:{contains:()=>locked,toggle(){}},querySelector(q){if(!fields.has(q))fields.set(q,el());return fields.get(q);},querySelectorAll:()=>[],append(){},appendChild(){},setAttribute(){},getAttribute:()=>null,blur(){},addEventListener(t,f){this.listeners.set(t,f);},dispatchEvent(e){this.listeners.get(e.type)?.(e);},click(){this.dispatchEvent({type:'click',preventDefault(){},stopPropagation(){}});}};}
 const panel=el(),win={addEventListener(t,f){const a=handlers.get(t)||[];a.push(f);handlers.set(t,a);},dispatchEvent(e){events.push(e);for(const f of handlers.get(e.type)||[])f(e);}};
 const document={createElement:t=>t==='div'?panel:el(),head:el(),querySelector:q=>{if(!fields.has(q))fields.set(q,el());return fields.get(q);},querySelectorAll:()=>[],addEventListener(){}};
 const mesh={clone:()=>({snapshot:true}),offsetEdgeLoopInfo:()=>({})};let faceTool='extrude',dragging=false;
 const c={document,window:win,THREE:{},placeToolSessionPanel(){},queueMicrotask:f=>jobs.push(f),requestAnimationFrame:f=>{jobs.push(f);return jobs.length;},cancelAnimationFrame(){},Event:class{constructor(type){this.type=type;}},CustomEvent:class{constructor(type,{detail}){Object.assign(this,{type,detail});}},__boxlabSelectionBridge:{mode:()=>mode,indices:()=>ids,set:(m,v)=>{calls.push(['selection',m,[...v]]);ids=[...v];}},__boxlabBridgeState:{mesh},__boxlabObjectManager:{activeId:1},__boxlabTransformArming:{disarm:()=>calls.push('transform-off')},__boxlabTotalGizmo:{setHubState:()=>calls.push('puck')},__boxlabComponentSlide:{disarmEdge:()=>calls.push('slide-off')},__boxlabOffsetLoop:{isArmed:()=>true,disarm:()=>calls.push('offset-off')},__boxlabPrecisionEdgeSlide:{apply:v=>{calls.push(['slide',v]);win.dispatchEvent({type:'boxlab-edge-slide-complete',detail:{ids:[3,4]}});return true;}},__boxlabPrecisionOffsetLoop:{apply:v=>{calls.push(['offset',v]);win.dispatchEvent({type:'boxlab-offset-loop-complete',detail:{created:[5,6]}});return true;}},__boxlabMainDirectTool:{applyCreaseSelection:(v,p,options)=>{if(options.pushHistory)c.__boxlabHistory.push({snapshot:true});calls.push(['crease',[...v],p]);return true;}},__boxlabHistory:{push:v=>calls.push(['old-history',v])},__boxlabFaceDirect:{tool:()=>faceTool,dragging:()=>dragging,clearTransformSuspension:()=>calls.push('suspension-off')},__boxlabPrecisionFace:{value:()=>.2,applyFor:(t,v)=>calls.push(['face',t,v])},__boxlabRepeatFacePrevious:{isArmed:()=>false,arm:()=>calls.push('repeat'),disarm:()=>calls.push('repeat-off')}};
 win.addEventListener('boxlab-selection-hub-session-complete',e=>{if(e.detail?.mode==='edge')calls.push('puck');});
 vm.runInNewContext(read(file).replace(/^import .*\n/gm,''),c);
 const input=(q,v)=>{const n=fields.get(q);n.value=v;n.dispatchEvent({type:'input'});};
 const click=q=>fields.get(q).click();const flush=()=>{const batch=jobs.splice(0);batch.forEach(f=>f());};
 return{c,panel,fields,calls,events,click,input,flush,emit:(t,detail)=>win.dispatchEvent({type:t,detail}),mode:v=>mode=v,ids:v=>ids=v,lock:v=>locked=v,drag:v=>dragging=v};
}
for(const [file,key,number,apply,complete,created] of [['selection-hub-slide-session.js','__boxlabSlideViewportSession','.shss-number','.shss-apply','boxlab-edge-slide-complete',[3,4]],['selection-hub-offset-session.js','__boxlabOffsetViewportSession','.shos-number','.shos-apply','boxlab-offset-loop-complete',[5,6]]]){
 test(file+': exact delegates once, retains result and exits to puck',()=>{const f=fixture(file);assert.equal(f.c[key].openFromHub(),true);f.input(number,'25');f.click(apply);assert.equal(f.c[key].active(),false);f.flush();assert.deepEqual(f.calls.filter(x=>Array.isArray(x)&&x[0]==='selection').at(-1),['selection','edge',created]);assert.equal(f.calls.filter(x=>x==='puck').length,1);});
 test(file+': context loss prevents stale controls and deferred selection restoration',()=>{const f=fixture(file);f.c[key].openFromHub();f.c[key].close();f.c.__boxlabObjectManager.activeId=2;f.calls.length=0;f.flush();assert.deepEqual(f.calls,[]);f.c[key].openFromHub();f.lock(true);f.emit('boxlab-bridge-state');assert.equal(f.c[key].active(),false);f.input(number,'25');f.click(apply);assert.ok(!f.calls.some(x=>Array.isArray(x)&&['slide','offset'].includes(x[0])));});
 test(file+': superseding tool and empty selection never resurrect launch selection',()=>{const f=fixture(file);f.c[key].openFromHub();f.emit('boxlab-selection-hub-tool',{mode:'edge',tool:'Bevel'});f.flush();assert.ok(!f.calls.includes('puck'));f.c[key].openFromHub();f.ids([]);f.calls.length=0;f.c[key].close();f.flush();assert.ok(!f.calls.some(x=>Array.isArray(x)&&x[0]==='selection'));});
 test(file+': invalid exact input stays unavailable',()=>{const f=fixture(file);f.c[key].openFromHub();for(const v of ['', 'NaN','200']){f.input(number,v);assert.equal(f.fields.get(apply).disabled,true);f.click(apply);}assert.ok(!f.calls.some(x=>Array.isArray(x)&&['slide','offset'].includes(x[0])));});
}
test('Crease records one original-owner history entry before context switch and never alters new history',()=>{const f=fixture('selection-hub-crease-session.js');f.c.__boxlabCreaseViewportSession.openFromHub();f.c.__boxlabHistory.push=()=>f.calls.push('wrong-history');f.c.__boxlabObjectManager.activeId=2;f.emit('boxlab-bridge-state');f.flush();assert.equal(f.c.__boxlabCreaseViewportSession.active(),false);assert.equal(f.calls.filter(x=>Array.isArray(x)&&x[0]==='old-history').length,1);assert.ok(!f.calls.includes('wrong-history'));assert.ok(!f.calls.includes('puck'));f.c.__boxlabCreaseViewportSession.close();assert.equal(f.calls.filter(x=>Array.isArray(x)&&x[0]==='old-history').length,1);});
test('Face dragging blocks Exact/Repeat/Done until original owner releases',()=>{const f=fixture('selection-hub-face-value-session.js');f.emit('boxlab-selection-hub-tool',{mode:'face',tool:'Extrude'});f.drag(true);f.c.__boxlabFaceValueViewportSession.sync();for(const q of ['input','.shfv-apply','.shfv-repeat','.shfv-done'])assert.equal(f.fields.get(q).disabled,true);f.calls.length=0;f.click('.shfv-apply');f.click('.shfv-repeat');assert.equal(f.c.__boxlabFaceValueViewportSession.close(),false);assert.deepEqual(f.calls,[]);f.drag(false);f.c.__boxlabFaceValueViewportSession.sync();f.click('.shfv-apply');assert.deepEqual(f.calls.find(x=>Array.isArray(x)),['face','extrude',.2]);f.c.__boxlabFaceValueViewportSession.close();assert.equal(f.c.__boxlabFaceValueViewportSession.active(),false);});
test('Face object/context loss closes settings without applying to new mesh',()=>{const f=fixture('selection-hub-face-value-session.js');f.emit('boxlab-selection-hub-tool',{mode:'face',tool:'Inset'});f.c.__boxlabBridgeState.mesh={};f.emit('boxlab-bridge-state');assert.equal(f.c.__boxlabFaceValueViewportSession.active(),false);f.click('.shfv-apply');assert.ok(!f.calls.some(x=>Array.isArray(x)&&x[0]==='face'));});
test('All four radial modes reject locked active object despite stale button enabled state',()=>{const sectors=['face','edge','vertex','object'].map(mode=>({dataset:{toolTarget:'#tool'},textContent:'Delete',classList:{toggle(){}},closest:()=>({dataset:{ringMode:mode}}),setAttribute(){},removeAttribute(){}}));const s=read('total-gizmo.js');vm.runInNewContext(s.slice(s.indexOf('function syncContextToolAvailability(){'),s.indexOf("activator?.addEventListener"))+'syncContextToolAvailability();',{toolSectors:sectors,document:{querySelector:q=>q==='#app'?{classList:{contains:()=>true}}:{disabled:false,classList:{contains:()=>false},getAttribute:()=>null}},__boxlabObjectRadialSession:{available:()=>true}});assert.ok(sectors.every(x=>x.disabled));});
test('Rejected contextual launch restores puck without broadcasting a launched tool',()=>{const s=read('total-gizmo.js'),handlers={},button={disabled:false,dataset:{toolTarget:'#align'},textContent:'Align',closest:()=>({dataset:{ringMode:'face'}}),addEventListener:(t,f)=>handlers[t]=f};const root={hidden:false},calls=[],c={toolSectors:[button],currentMode:()=> 'face',syncContextToolAvailability(){},document:{querySelector:()=>({disabled:false})},suspendedFaceTool:false,hubSuppressedKey:'',lastSelectionKey:'face:1',setHubState:(x,o)=>calls.push([x,o.reason]),root,gestureDebug(){},window:{dispatchEvent:()=>calls.push('event')},__boxlabFaceAlignViewportSession:{openFromHub:()=>false},state:()=>({mesh:{}}),selectionKey:()=> 'face:1',selectionAvailable:()=>true,status:{},CustomEvent:class{}};vm.runInNewContext(s.slice(s.indexOf('toolSectors.forEach(button=>{'),s.indexOf('toolButtons.forEach(button=>')),c);handlers.click({preventDefault(){},stopPropagation(){}});assert.equal(root.hidden,false);assert.equal(c.hubSuppressedKey,'');assert.ok(calls.some(x=>Array.isArray(x)&&x[1]==='tool-launch-rejected'));assert.ok(!calls.includes('event'));});


test('Edge Slide/Offset/Crease semantic completion clears radial suppression and returns surviving selection to puck',()=>{
 const s=read('total-gizmo.js'),a=s.indexOf("window.addEventListener('boxlab-selection-hub-session-complete'"),b=s.indexOf('\nfunction ',a);
 // Read exactly this listener, stopping before subsequent unrelated listeners.
 const chunk=s.slice(a,s.indexOf('\n});',a)+4);
 for(const tool of ['Slide','Offset','Crease']){let listener;const calls=[],root={hidden:true},c={window:{addEventListener:(t,f)=>listener=f},hubSuppressedKey:'edge:1',resetTransientState:()=>calls.push('reset'),selectionKey:()=> 'edge:1',state:()=>({mesh:{}}),currentMode:()=> 'edge',setHubState:x=>calls.push(x),selectionAvailable:()=>true,root};vm.createContext(c);vm.runInContext(chunk,c);listener({detail:{mode:'edge',tool}});assert.equal(c.hubSuppressedKey,'');assert.equal(root.hidden,false);assert.ok(calls.includes('closed'));}
});
