import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import { EditableMesh } from '../src/mesh.js';import { installBridgeTopology } from '../src/bridge-topology.js';import { installUnequalBridge } from '../src/bridge-unequal.js';import { installUnequalBridgeQuality } from '../src/bridge-unequal-quality.js';import { installUnequalBridgeAlignment } from '../src/bridge-unequal-alignment.js';import { installUnequalBridgeGlobal,validateGlobalBridgeCandidate,searchGlobalBridgeCorrespondence,bridgeSurfaceQualityPenalty } from '../src/bridge-unequal-global.js';import { installTransactionalBridge } from '../src/bridge-transactional.js';
installBridgeTopology(EditableMesh);installUnequalBridge(EditableMesh);installUnequalBridgeQuality(EditableMesh);installUnequalBridgeAlignment(EditableMesh);installUnequalBridgeGlobal(EditableMesh);installTransactionalBridge(EditableMesh);
function ring(count,z,{radius=1,rotation=0,offsetX=0,offsetY=0,stretchX=1,stretchY=1}={}){return Array.from({length:count},(_,i)=>{const a=rotation+Math.PI*2*i/count,w=i===1?1.35:1;return new THREE.Vector3(offsetX+Math.cos(a)*radius*stretchX*w,offsetY+Math.sin(a)*radius*stretchY,z);});}
function caps(aCount,bCount,topOptions={}){const bottom=ring(aCount,-1,{radius:1.1,stretchX:1.25,stretchY:.9}),top=ring(bCount,1,{radius:1,rotation:.57,offsetX:.42,offsetY:-.24,stretchX:.82,stretchY:1.22,...topOptions}),vertices=[...bottom,...top],bottomFace=Array.from({length:aCount},(_,i)=>aCount-1-i),topFace=Array.from({length:bCount},(_,i)=>aCount+i);return new EditableMesh(vertices,[bottomFace,topFace]);}
test('4 to 7 Bridge is globally matched, surface-scored, quad-dominant and closed',()=>{const mesh=caps(4,7),ids=mesh.edges().map((_,i)=>i),info=mesh.bridgeEdgeSelectionInfo(ids),plan=mesh.bestUnequalBridgePlan(info.loops[0],info.loops[1]);assert.equal(plan?.globalOptimized,true);assert.equal(plan.globalCorrespondence,true);assert.equal(plan.surfaceQualityCost,true);assert.equal(plan.qualityGuarded,true);assert.equal(plan.quadCount,4);assert.equal(plan.triangleCount,3);assert.ok(plan.candidatesTried>=14);assert.ok(plan.candidatesValid>0);const result=mesh.bridgeSelectedEdges(ids);assert.equal(result?.plan?.surfaceQualityCost,true);assert.equal(globalThis.__boxlabTopology.validateTopology(mesh,{allowBoundary:false}).ok,true);assert.equal(globalThis.__boxlabBridgeTransaction?.ok,true);});
test('5 to 8 rotated Bridge searches all cyclic correspondences deterministically',()=>{const mesh=caps(5,8,{rotation:.94,offsetX:-.38,offsetY:.31}),ids=mesh.edges().map((_,i)=>i),info=mesh.bridgeEdgeSelectionInfo(ids),first=mesh.bestUnequalBridgePlan(info.loops[0],info.loops[1]),second=mesh.bestUnequalBridgePlan(info.loops[0],info.loops[1]);assert.equal(first?.globalCorrespondence,true);assert.equal(first.surfaceQualityCost,true);assert.equal(first.qualityGuarded,true);assert.equal(first.quadCount,5);assert.equal(first.triangleCount,3);assert.equal(first.candidatesTried,16);assert.ok(first.candidatesValid>0);assert.deepEqual(first.faces,second.faces);assert.equal(first.offset,second.offset);assert.equal(first.direction,second.direction);});
test('direct correspondence search evaluates both loop directions and every offset',()=>{const mesh=caps(4,7,{rotation:1.31,offsetX:.65,offsetY:.18,stretchX:1.18,stretchY:.72}),ids=mesh.edges().map((_,i)=>i),info=mesh.bridgeEdgeSelectionInfo(ids),base=mesh.bestUnequalBridgePlan(info.loops[0],info.loops[1]);assert.equal(base.globalCorrespondence,true);const search=searchGlobalBridgeCorrespondence(mesh,info.loops[0],info.loops[1],!!base.flip,Infinity);assert.equal(search.tried,14);assert.ok(search.valid>0);assert.ok(search.best);});
test('surface quality cost prefers balanced planar quad to twisted quad',()=>{const balanced={vertices:[new THREE.Vector3(0,0,0),new THREE.Vector3(1,0,0),new THREE.Vector3(1,1,0),new THREE.Vector3(0,1,0)]},twisted={vertices:[new THREE.Vector3(0,0,0),new THREE.Vector3(1,0,0),new THREE.Vector3(1,1,1.4),new THREE.Vector3(0,1,0)]};assert.ok(bridgeSurfaceQualityPenalty(balanced,[0,1,2,3],1)<bridgeSurfaceQualityPenalty(twisted,[0,1,2,3],1));});
test('surface quality cost penalises skinny triangle',()=>{const good={vertices:[new THREE.Vector3(0,0,0),new THREE.Vector3(1,0,0),new THREE.Vector3(.5,.866,0)]},skinny={vertices:[new THREE.Vector3(0,0,0),new THREE.Vector3(2,0,0),new THREE.Vector3(.03,.02,0)]};assert.ok(bridgeSurfaceQualityPenalty(good,[0,1,2],1)<bridgeSurfaceQualityPenalty(skinny,[0,1,2],1));});
test('quality guard rejects degenerate candidate faces',()=>{const mesh={vertices:[new THREE.Vector3(0,0,0),new THREE.Vector3(1,0,0),new THREE.Vector3(2,0,0),new THREE.Vector3(3,0,0)]};const result=validateGlobalBridgeCandidate(mesh,[[0,1,2,3]],[0,1],[2,3],1);assert.equal(result.ok,false);assert.match(result.reason,/degenerate/);});
test('quality guard rejects extreme connector distortion',()=>{const mesh={vertices:[new THREE.Vector3(0,0,0),new THREE.Vector3(1,0,0),new THREE.Vector3(100,1,0)]};const result=validateGlobalBridgeCandidate(mesh,[[0,1,2]],[0,1],[2],1);assert.equal(result.ok,false);assert.equal(result.reason,'connector-distortion');});
test('equal-count Bridge stays on proven equal solver',()=>{const mesh=caps(4,4),ids=mesh.edges().map((_,i)=>i),result=mesh.bridgeSelectedEdges(ids);assert.ok(result);assert.equal(result.unequal,undefined);assert.equal(result.plan?.globalOptimized,undefined);assert.equal(result.faceIndices.length,4);});
