import * as THREE from 'three';
const button=document.querySelector('#bevelBtn'),canvas=document.querySelector('#viewport'),width=document.querySelector('#bevelWidth'),out=document.querySelector('#bevelWidthOut'),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();ray.params.Line.threshold=.09;let armed=false,drag=null;
function state(){return globalThis.__boxlabBridgeState}function bridge(){return globalThis.__boxlabSelectionBridge}function hit(e){const s=state(),r=canvas.getBoundingClientRect();if(!s?.camera)return null;pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,s.camera);const h=ray.intersectObjects([...(s.edgeObjects?.values()||[])],false)[0];return Number.isInteger(h?.object?.userData?.index)?h.object.userData.index:null}
function disarm(){armed=false;drag=null;button?.classList.remove('active');}
button?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();armed=!armed;document.querySelector('#selectionModes button[data-mode="edge"]')?.click();bridge()?.set?.('edge',[]);button.classList.toggle('active',armed);document.querySelector('#selectionStatus').textContent=armed?'Bevel Edge • tap an edge, then drag width':'Edge mode • nothing selected'},true);
document.addEventListener('click',e=>{if(!armed||!e.isTrusted||e.target?.closest?.('#bevelBtn'))return;if(e.target?.closest?.('button'))disarm();},true);
function restore(mesh,snapshot){mesh.vertices=snapshot.vertices.map(v=>v.clone());mesh.faces=snapshot.faces.map(f=>[...f]);mesh.creases=new Map(snapshot.creases)}function render(){document.querySelector('#cageToggle')?.dispatchEvent(new Event('change',{bubbles:true}))}
canvas?.addEventListener('pointerdown',e=>{if(!armed||!e.isPrimary)return;const i=hit(e),mesh=state()?.mesh;if(!Number.isInteger(i)||!mesh)return;e.preventDefault();e.stopImmediatePropagation();bridge()?.add?.('edge',i);const valid=mesh.generalBevelSelectionInfo?.([i]);if(!valid)return;drag={id:e.pointerId,x:e.clientX,width:Number(width.value||20),mesh,before:mesh.clone(),ids:valid.ids,preview:false};canvas.setPointerCapture?.(e.pointerId)},true);
canvas?.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const value=Math.max(2,Math.min(45,drag.width+(e.clientX-drag.x)*.25)),amount=Math.round(value);width.value=String(amount);out.textContent=`${amount}%`;restore(drag.mesh,drag.before);drag.preview=!!drag.mesh.generalBevelSelection?.(drag.ids,amount/100,Math.max(1,Number(document.querySelector('#bevelSegments')?.value||1)));render()},true);
canvas?.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const current=drag;drag=null;if(current.preview)globalThis.__boxlabHistory?.push(current.before);else restore(current.mesh,current.before);render()},true);
