import * as THREE from 'three';

const canvas=document.querySelector('#viewport');
const button=document.querySelector('#knifeBtn');
const status=document.querySelector('#selectionStatus');
const ray=new THREE.Raycaster();
const pointer=new THREE.Vector2();
const VERTEX_SNAP_PX=16;
const EDGE_PICK_PX=26;
const MIN_DRAG_PX=12;
const INFERENCE_MIN_PX=18;
const INFERENCE_ANGLE_DEG=14;
const INFERENCE_START_EPS_PX=8;
let armed=false,drag=null,preview=null,startMarker=null,endMarker=null;

function state(){return globalThis.__boxlabBridgeState;}
function bridge(){return globalThis.__boxlabSelectionBridge;}
function render(){document.querySelector('#cageToggle')?.dispatchEvent(new Event('change',{bubbles:true}));}
function inferenceOn(){return !!document.querySelector('#inferenceSnapToggle')?.checked;}
function edgeKey(mesh,e){return mesh.edgeKey(e.a,e.b);}
function screenPoint(v,camera){const p=v.clone().project(camera),r=canvas.getBoundingClientRect();return{x:r.left+(p.x*.5+.5)*r.width,y:r.top+(-p.y*.5+.5)*r.height};}
function distSeg(px,py,a,b){const vx=b.x-a.x,vy=b.y-a.y,l2=vx*vx+vy*vy;if(!l2)return{d:Math.hypot(px-a.x,py-a.y),t:0,q:{x:a.x,y:a.y}};const t=Math.max(0,Math.min(1,((px-a.x)*vx+(py-a.y)*vy)/l2)),q={x:a.x+vx*t,y:a.y+vy*t};return{d:Math.hypot(px-q.x,py-q.y),t,q};}
function hitFace(event){const s=state(),mesh=s?.mesh,camera=s?.camera;if(!mesh||!camera)return null;const r=canvas.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-((event.clientY-r.top)/r.height*2-1));ray.setFromCamera(pointer,camera);const geometry=mesh.triangulatedGeometry(),material=new THREE.MeshBasicMaterial({side:THREE.DoubleSide}),picker=new THREE.Mesh(geometry,material),hit=ray.intersectObject(picker,false)[0];geometry.dispose();material.dispose();if(!hit)return null;let tri=hit.faceIndex,faceIndex=-1;for(let fi=0;fi<mesh.faces.length;fi++){const n=Math.max(0,mesh.faces[fi].length-2);if(tri<n){faceIndex=fi;break;}tri-=n;}return faceIndex>=0?{faceIndex,point:hit.point.clone()}:null;}
function boundaryPoint(faceIndex,x,y){const s=state(),mesh=s?.mesh,camera=s?.camera,face=mesh?.faces?.[faceIndex];if(!mesh||!camera||!face)return null;let bestVertex=null,bestEdge=null;for(let i=0;i<face.length;i++){const a=face[i],b=face[(i+1)%face.length],pa=screenPoint(mesh.vertices[a],camera),pb=screenPoint(mesh.vertices[b],camera),seg=distSeg(x,y,pa,pb),da=Math.hypot(x-pa.x,y-pa.y),db=Math.hypot(x-pb.x,y-pb.y);if(da<=VERTEX_SNAP_PX&&(!bestVertex||da<bestVertex.d))bestVertex={kind:'vertex',vertex:a,d:da,screen:pa};if(db<=VERTEX_SNAP_PX&&(!bestVertex||db<bestVertex.d))bestVertex={kind:'vertex',vertex:b,d:db,screen:pb};if(seg.d<=EDGE_PICK_PX&&(!bestEdge||seg.d<bestEdge.d))bestEdge={kind:'edge',key:mesh.edgeKey(a,b),faceA:a,faceB:b,t:seg.t,d:seg.d,screen:seg.q};}return bestVertex||bestEdge;}
function inferredAxis(dx,dy){const len=Math.hypot(dx,dy);if(len<INFERENCE_MIN_PX)return null;const angle=Math.atan2(Math.abs(dy),Math.abs(dx))*180/Math.PI;if(angle<=INFERENCE_ANGLE_DEG)return'horizontal';if(angle>=90-INFERENCE_ANGLE_DEG)return'vertical';return null;}
function lineEdgeIntersection(start,axis,a,b){const eps=1e-7;if(axis==='horizontal'){const dy=b.y-a.y;if(Math.abs(dy)<eps)return null;const t=(start.y-a.y)/dy;if(t<-eps||t>1+eps)return null;return{x:a.x+(b.x-a.x)*t,y:start.y,t:THREE.MathUtils.clamp(t,0,1)};}const dx=b.x-a.x;if(Math.abs(dx)<eps)return null;const t=(start.x-a.x)/dx;if(t<-eps||t>1+eps)return null;return{x:start.x,y:a.y+(b.y-a.y)*t,t:THREE.MathUtils.clamp(t,0,1)};}
function inferredBoundaryPoint(faceIndex,start,event){if(!inferenceOn())return null;const axis=inferredAxis(event.clientX-start.screen.x,event.clientY-start.screen.y);if(!axis)return null;const s=state(),mesh=s?.mesh,camera=s?.camera,face=mesh?.faces?.[faceIndex];if(!mesh||!camera||!face)return null;const dx=event.clientX-start.screen.x,dy=event.clientY-start.screen.y,sign=axis==='horizontal'?Math.sign(dx||1):Math.sign(dy||1);let best=null;for(let i=0;i<face.length;i++){const va=face[i],vb=face[(i+1)%face.length],a=screenPoint(mesh.vertices[va],camera),b=screenPoint(mesh.vertices[vb],camera),hit=lineEdgeIntersection(start.screen,axis,a,b);if(!hit)continue;const along=axis==='horizontal'?hit.x-start.screen.x:hit.y-start.screen.y;if(Math.abs(along)<=INFERENCE_START_EPS_PX||Math.sign(along)!==sign)continue;const vertexA=Math.hypot(hit.x-a.x,hit.y-a.y),vertexB=Math.hypot(hit.x-b.x,hit.y-b.y);let snap;if(vertexA<=VERTEX_SNAP_PX)snap={kind:'vertex',vertex:va,d:vertexA,screen:a,inference:axis};else if(vertexB<=VERTEX_SNAP_PX)snap={kind:'vertex',vertex:vb,d:vertexB,screen:b,inference:axis};else snap={kind:'edge',key:mesh.edgeKey(va,vb),faceA:va,faceB:vb,t:hit.t,d:0,screen:{x:hit.x,y:hit.y},inference:axis};const pointerDistance=Math.hypot(event.clientX-snap.screen.x,event.clientY-snap.screen.y);if(!best||pointerDistance<best.pointerDistance)best={...snap,pointerDistance};}return best;}
function endpointFor(faceIndex,start,event){return inferredBoundaryPoint(faceIndex,start,event)||boundaryPoint(faceIndex,event.clientX,event.clientY);}
function splitFaceEdge(face,a,b,vertex){for(let i=0;i<face.length;i++){const x=face[i],y=face[(i+1)%face.length];if((x===a&&y===b)||(x===b&&y===a)){const out=[...face];out.splice(i+1,0,vertex);return out;}}return face;}
function splitEdge(mesh,snap){const edge=mesh.edges().find(e=>edgeKey(mesh,e)===snap.key);if(!edge)return null;let t=snap.t;if(edge.a===snap.faceB&&edge.b===snap.faceA)t=1-t;const {a,b}=edge,crease=mesh.creases?.get(snap.key)||0,vertex=mesh.vertices.length;mesh.vertices.push(mesh.vertices[a].clone().lerp(mesh.vertices[b],THREE.MathUtils.clamp(t,.001,.999)));for(const fi of edge.faces||[])if(Array.isArray(mesh.faces[fi]))mesh.faces[fi]=splitFaceEdge(mesh.faces[fi],a,b,vertex);if(mesh.creases instanceof Map){mesh.creases.delete(snap.key);if(crease>0){mesh.creases.set(mesh.edgeKey(a,vertex),crease);mesh.creases.set(mesh.edgeKey(vertex,b),crease);}}return vertex;}
function resolveEndpoint(mesh,snap){return snap.kind==='vertex'?snap.vertex:splitEdge(mesh,snap);}
function restore(mesh,before){mesh.vertices=before.vertices.map(v=>v.clone());mesh.faces=before.faces.map(f=>[...f]);mesh.creases=new Map(before.creases);if(before.looseEdges instanceof Set)mesh.looseEdges=new Set(before.looseEdges);if(before.looseVertices instanceof Set)mesh.looseVertices=new Set(before.looseVertices);}
function clearPreview(){preview?.remove();preview=null;startMarker?.remove();startMarker=null;endMarker?.remove();endMarker=null;}
function marker(point,kind){const el=document.createElement('div'),size=kind==='vertex'?12:8;el.style.cssText=`position:fixed;pointer-events:none;width:${size}px;height:${size}px;border-radius:50%;border:2px solid ${kind==='vertex'?'#ffffff':'#ffe14a'};background:${kind==='vertex'?'#ffe14a':'#111318'};box-shadow:0 0 0 2px #0008;z-index:10000;transform:translate(-50%,-50%)`;el.style.left=`${point.x}px`;el.style.top=`${point.y}px`;document.body.appendChild(el);return el;}
function showPreview(start,endSnap,fallback){clearPreview();startMarker=marker(start.screen,start.kind);const b=endSnap?.screen||fallback;const el=document.createElement('div');el.style.cssText=`position:fixed;pointer-events:none;height:2px;background:${endSnap?.inference?'#62d8ff':'#ffe14a'};transform-origin:0 50%;z-index:9999;box-shadow:0 0 4px #0008`;const dx=b.x-start.screen.x,dy=b.y-start.screen.y;el.style.left=`${start.screen.x}px`;el.style.top=`${start.screen.y}px`;el.style.width=`${Math.hypot(dx,dy)}px`;el.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;document.body.appendChild(el);preview=el;if(endSnap)endMarker=marker(endSnap.screen,endSnap.kind);}
function snapLabel(snap){const base=snap?.kind==='vertex'?'VERTEX SNAP':snap?.kind==='edge'?'EDGE SNAP':'NO SNAP';return snap?.inference?`${base} • ${snap.inference.toUpperCase()}`:base;}
function disarm(){armed=false;drag=null;clearPreview();button?.classList.remove('active');}
function disableMulti(){const multi=document.querySelector('#multiSelectToggle');if(multi?.checked){multi.checked=false;multi.dispatchEvent(new Event('change',{bubbles:true}));}}
function disarmOtherTools(){globalThis.__boxlabTransformArming?.disarm?.();document.querySelectorAll('#toolModes button,#extrudeBtn,#insetBtn').forEach(b=>b.classList.remove('active'));document.dispatchEvent(new CustomEvent('boxlab-direct-tool-exclusive',{detail:{tool:'knife'}}));}

button?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();armed=!armed;drag=null;clearPreview();if(armed){disableMulti();disarmOtherTools();if(bridge()?.mode?.()!=='face')document.querySelector('#selectionModes button[data-mode="face"]')?.click();}button.classList.toggle('active',armed);if(status)status.textContent=armed?`Knife • vertex priority • edge snap • ${inferenceOn()?'Inference horizontal/vertical ON':'Inference OFF'}`:'Face mode • Knife off';},true);
document.addEventListener('click',e=>{if(!armed||!e.isTrusted||e.target?.closest?.('#knifeBtn'))return;const otherTool=e.target?.closest?.('#extrudeBtn,#insetBtn,#toolModes button,#vertexBevelBtn,#bevelBtn,#edgeSlideBtn,#offsetLoopBtn,#loopCutBtn,#faceSplitBtn,#extractFacesBtn,#bridgeFacesBtn,#deleteFaceBtn');if(otherTool)disarm();},true);
document.addEventListener('boxlab-direct-tool-exclusive',event=>{if(event.detail?.tool&&event.detail.tool!=='knife')disarm();},true);

canvas?.addEventListener('pointerdown',e=>{if(!armed||!e.isPrimary||e.pointerType==='touch'||(e.pointerType==='pen'&&!(e.pressure>0)))return;const face=hitFace(e);if(!face)return;const start=boundaryPoint(face.faceIndex,e.clientX,e.clientY);if(!start)return;e.preventDefault();e.stopImmediatePropagation();drag={id:e.pointerId,faceIndex:face.faceIndex,x:e.clientX,y:e.clientY,start};showPreview(start,null,start.screen);if(status)status.textContent=`Knife start • ${snapLabel(start)} • drag${inferenceOn()?' near horizontal/vertical to infer':''}`;canvas.setPointerCapture?.(e.pointerId);},true);
canvas?.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();const end=endpointFor(drag.faceIndex,drag.start,e);showPreview(drag.start,end,{x:e.clientX,y:e.clientY});if(status)status.textContent=end?`Knife end • ${snapLabel(end)} • release to cut`:'Knife • move onto a boundary snap before releasing';},true);
canvas?.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;clearPreview();e.preventDefault();e.stopImmediatePropagation();try{canvas.releasePointerCapture?.(e.pointerId);}catch{}if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<MIN_DRAG_PX)return;const s=state(),mesh=s?.mesh;if(!mesh)return;const end=endpointFor(d.faceIndex,d.start,e);if(!end){if(status)status.textContent='Knife • release only after a vertex or edge snap appears';return;}if(d.start.kind==='vertex'&&end.kind==='vertex'&&d.start.vertex===end.vertex)return;if(d.start.kind==='edge'&&end.kind==='edge'&&d.start.key===end.key)return;const before=mesh.clone(),a=resolveEndpoint(mesh,d.start),b=resolveEndpoint(mesh,end),result=Number.isInteger(a)&&Number.isInteger(b)&&a!==b?mesh.connectVertices(a,b):null;if(!result?.ok){restore(mesh,before);render();if(status)status.textContent='Knife could not make a clean cut • use two different snapped face boundaries';return;}globalThis.__boxlabHistory?.push(before);render();if(bridge()?.mode?.()!=='face')document.querySelector('#selectionModes button[data-mode="face"]')?.click();button?.classList.add('active');armed=true;if(status)status.textContent=`Knife cut committed • ${snapLabel(d.start)} → ${snapLabel(end)} • Knife remains active`;},true);
canvas?.addEventListener('pointercancel',e=>{if(drag?.id!==e.pointerId)return;drag=null;clearPreview();},true);
